metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1

compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "localhost:3901"
# rpc_secret = ""

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.127.0.0.1.traefik.me"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.127.0.0.1.traefik.me"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
# admin_token=""
# metrics_token = ""
